/-
Copyright (c) 2026 ASTER LAB. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ASTER LAB
-/
import Phylo.ConsensusExtra

/-!
# `Phylo.Stat.Bootstrap` —— bootstrap 支持度（Felsenstein 1985）

文献：J. Felsenstein, *Confidence limits on phylogenies: an approach using the bootstrap*,
**Evolution 39**(4) (1985) 783–791。
文本见 `references/md/Felsenstein1985_ConfidenceLimitsPhylogeniesBootstrap.md`
（md5 `e8b363f79343ca89650f9faf82c538c3`，2097 行）。
**下文行号一律指该 md 的行号**（OCR 有损；逐字引用处以 `>` 标出）。

## 0. 原文定义（本文件的全部口径来源）

**重抽样的对象是「字符」而不是「物种」**（L14–17）：

> "the proper method of resampling is to keep all of the original species while sampling
> characters with replacement"

**一次 bootstrap 样本**（L298–307）：

> "a justifiable procedure is to bootstrap across the characters, that is, to sample
> characters (or sites) from the data table with replacement. Thus, each bootstrap sample
> consists of a new data table with the same set of species, but with some of the original
> characters duplicated and others dropped by the process of sampling n characters from the
> original set with replacement."

**权重向量口径**（L1276–1283，也正是本文件 `weightOf` 的出处）：

> "The weights are generated by starting with weights of zero for all characters. We then
> sample n characters at random with replacement ... Each time a character is drawn, its
> weight is increased by one, so that in the end its weight counts the number of times it
> was sampled."

论文摘要 L20–22 把这一点说成了程序接口：

> "Existing computer programs can be used to analyze different bootstrap samples by using
> weights on the characters, the weight of a character being how many times it was drawn
> in bootstrap sampling."

**支持度 = 出现在多少棵重抽样树里**（L717–720、L743–747）：

> "We thus wish to search for all subsets S of species that occur on 95% or more of the
> bootstrap estimates."
> "If we take the set of phylogenies that result from analyzing a series of bootstrap samples
> and make a majority-rule consensus tree, recording on it how often each subset appears,
> we will obtain a tree that can be used to define at a glance confidence sets for any
> rejection probability below 50%."

## 1. 本文件证什么

```
① 权重载体     Σᵢ wᵢ = n                       （L1276–1283 的有限组合内容）
② 支持度       bootstrapSupport ∈ [0,1]         （L717–720 的「比例」）
③ 端点         支持度 = 1 ⟺ 每次都展示；= 0 ⟺ 从不展示
④ 阈值桥       支持度 > 1/2 ⟺ 库内 IsMajority   （Phylo/Consensus.lean:40）
⑤ 相容性       支持度 > 1/2 的 split 两两相容   （鸽笼原理）
⑥ 共识树存在   Felsenstein L743–753 的 "overall bootstrap estimate of the phylogeny"
⑦ 期望         ★★★ 线性字符统计量的重抽样均值 = 原数据的值（L234–245 的多项式均值）
──────────────────────────────────────────────────────────
⑧ 最小例子（★C）4 taxa / 3 字符 / 27 次重抽样，精确计数 13
```

## 2. ⚠️ 诚实边界（★B：先造反例）

**反例 1（§5 机器验证）**：`bootstrapSupport` 是**重抽样树族中的频率**，
**不是**「该 split 为真」的概率，也**不**保证原数据报告的 split 有 `≥ 50%` 的支持度。
§5 给出一个完全显式的例子：4 taxa、3 字符、27 次重抽样下，
**原数据报告的 split 的支持度恰为 `13/27 < 1/2`** —— 它**不在**多数共识树里。

**反例 2（§4）**：「重抽样下支持度的期望 = 原数据的频率」**为假** ——
建树规则 `Tree` 一般**非线性**，故 `E[1{s ∈ Tree(w)}] ≠ 1{s ∈ Tree(原数据)}`。
**正确的**（也是可证的）陈述在**线性层**：字符权重的期望 = 原数据的经验频率（§4）。

**反例 3（结构性）**：上面两条都不是「未想到」，而是 Felsenstein 本人写下的（L776–783）：

> "Bootstrapping provides us with a confidence interval within which is contained not the
> true phylogeny, but the phylogeny that would be estimated on repeated sampling of many
> characters from the underlying pool of characters. As such it may be misleading if the
> method used to infer phylogenies is inconsistent."

把频率读成置信度的**渐近统计**内容本库没有（见 §6 缺口 C），
本文件**只**证纯组合 → 有限事实。

## 3. 新增 import

**无**。`import Phylo.ConsensusExtra` 已带齐全部零件（`supportCount` / `IsMajority` /
`majoritySplits` / `majority_compatible` / `majority_consensus_exists` / `pairwiseCompatible`）。
**未新增任何 Mathlib import**（代价：本文件只用 `norm_num` / `decide` / `push_cast` /
`exact_mod_cast` / `omega` / `mul_lt_mul_of_pos_left`，**不用** `ring` / `linarith` /
`field_simp` —— 它们不在该 import 闭包内；见 `half_mul_two_mul` 与 §5 的 `div_lt_div_iff₀` 用法）。
-/

universe u

namespace Phylo.Stat.Bootstrap

/-! ## §1 重抽样的有限载体（L1276–1283） -/

/-- 一次重抽样编码为映射：`σ j` 是第 `j` 次抽中的字符下标。

⚠️ 「有放回」由「`σ` 只要求是**函数**（不受单射约束）」承载：同一下标可以被抽中多次。 -/
abbrev Resample (n : ℕ) := Fin n → Fin n

/-- **权重向量**（L1276–1283 的 "weights"）：字符 `i` 被抽中的次数。 -/
def weightOf {n : ℕ} (σ : Resample n) : Fin n → ℕ :=
  fun i => (Finset.univ.filter fun j => σ j = i).card

/-- ★ **权重和恒为 `n`**（「抽了 `n` 次」+「每次给某个字符的权重 `+1`」）。

按函数的纤维作划分：`∑ᵢ #{j | σ j = i} = #{j} = n`。 -/
theorem sum_weightOf {n : ℕ} (σ : Resample n) : ∑ i, weightOf σ i = n := by
  classical
  have h := Finset.card_eq_sum_card_fiberwise
    (s := (Finset.univ : Finset (Fin n))) (t := (Finset.univ : Finset (Fin n)))
    (f := σ) (fun j _ => Finset.mem_univ (σ j))
  simpa only [weightOf, Finset.card_univ, Fintype.card_fin] using h.symm

/-- **合法权重向量**：和恰为 `n` 的 `ℕ`-向量。

⚠️ 本文件**不**断言「合法 ⟺ 可由某次重抽样实现」——那需要多项式系数记账，
见 §6 缺口 M。 -/
def IsBootstrapWeight {n : ℕ} (w : Fin n → ℕ) : Prop := ∑ i, w i = n

/-- `weightOf` 的像落在合法权重向量里（`sum_weightOf` 的重述）。 -/
theorem isBootstrapWeight_weightOf {n : ℕ} (σ : Resample n) :
    IsBootstrapWeight (weightOf σ) := sum_weightOf σ

/-! ## §2 bootstrap 支持度（L717–720） -/

variable {X : Type u} [Fintype X] [DecidableEq X]

/-- ★ **bootstrap 支持度**（L717–720 的 "occur on ... of the bootstrap estimates" 的比例版）：
树族 `T` 中展示 `s` 的树所占比例，取值在 `ℚ`。

⚠️ `T` 的指标类型 `ι` 就是**重抽样编号**（`T i` = 第 `i` 次重抽样建出的树），
`Fintype.card ι` = 重抽样次数 `r`（论文取 50，见 L1302）。 -/
noncomputable def bootstrapSupport {ι : Type*} [Fintype ι] [DecidableEq ι]
    (T : ι → Cladogram X) (s : Split X) : ℚ :=
  (supportCount T s : ℚ) / (Fintype.card ι : ℚ)

/-- 支持计数不超过树数（支持度 `≤ 1` 的组合内核）。 -/
theorem supportCount_le_card {ι : Type*} [Fintype ι] [DecidableEq ι]
    (T : ι → Cladogram X) (s : Split X) : supportCount T s ≤ Fintype.card ι := by
  classical
  simp only [supportCount]
  calc (Finset.univ.filter fun i => (T i).IsSplitOf s).card
      ≤ (Finset.univ : Finset ι).card := Finset.card_le_card (Finset.filter_subset _ _)
    _ = Fintype.card ι := Finset.card_univ

theorem bootstrapSupport_nonneg {ι : Type*} [Fintype ι] [DecidableEq ι]
    (T : ι → Cladogram X) (s : Split X) : 0 ≤ bootstrapSupport T s := by
  rw [bootstrapSupport]
  exact div_nonneg (Nat.cast_nonneg _) (Nat.cast_nonneg _)

theorem bootstrapSupport_le_one {ι : Type*} [Fintype ι] [DecidableEq ι] [Nonempty ι]
    (T : ι → Cladogram X) (s : Split X) : bootstrapSupport T s ≤ 1 := by
  have hk : (0 : ℚ) < (Fintype.card ι : ℚ) := by
    exact_mod_cast (Fintype.card_pos_iff.mpr ‹Nonempty ι› : 0 < Fintype.card ι)
  rw [bootstrapSupport, div_le_one hk]
  exact_mod_cast supportCount_le_card T s

/-- ★★ **支持度总在 `[0,1]`**。

★B 反问「支持度真的在 `[0,1]` 吗？边界何时取到？」的答案：
在 `[0,1]` 内（本条），且**两端都取得到** —— `= 1` ⟺ 每次重抽样都展示它
（`bootstrapSupport_eq_one_iff`），`= 0` ⟺ 从不展示它（`bootstrapSupport_eq_zero_iff`）。 -/
theorem bootstrapSupport_mem_unit {ι : Type*} [Fintype ι] [DecidableEq ι] [Nonempty ι]
    (T : ι → Cladogram X) (s : Split X) : bootstrapSupport T s ∈ Set.Icc (0 : ℚ) 1 :=
  ⟨bootstrapSupport_nonneg T s, bootstrapSupport_le_one T s⟩

/-- 支持计数取满 ⟺ 每棵树都展示 `s`（有限全称的鸽笼形式）。 -/
theorem supportCount_eq_card_iff {ι : Type*} [Fintype ι] [DecidableEq ι]
    (T : ι → Cladogram X) (s : Split X) :
    supportCount T s = Fintype.card ι ↔ ∀ i, (T i).IsSplitOf s := by
  classical
  constructor
  · intro h i
    have hcard : (Finset.univ.filter fun k => (T k).IsSplitOf s).card
        = (Finset.univ : Finset ι).card := by
      simpa only [supportCount, Finset.card_univ] using h
    have huniv : Finset.univ.filter (fun k => (T k).IsSplitOf s) = Finset.univ :=
      Finset.eq_of_subset_of_card_le (Finset.filter_subset _ _) (le_of_eq hcard.symm)
    have hmem : i ∈ Finset.univ.filter (fun k => (T k).IsSplitOf s) := by
      rw [huniv]
      exact Finset.mem_univ i
    exact (Finset.mem_filter.mp hmem).2
  · intro h
    simp only [supportCount]
    rw [Finset.filter_true_of_mem (fun i _ => h i), Finset.card_univ]

/-- ★ **支持度 `= 1` ⟺ 每一次重抽样都展示它**（上界取到的唯一方式）。 -/
theorem bootstrapSupport_eq_one_iff {ι : Type*} [Fintype ι] [DecidableEq ι] [Nonempty ι]
    (T : ι → Cladogram X) (s : Split X) :
    bootstrapSupport T s = 1 ↔ ∀ i, (T i).IsSplitOf s := by
  have hk : ((Fintype.card ι : ℕ) : ℚ) ≠ 0 := by
    exact_mod_cast (ne_of_gt (Fintype.card_pos_iff.mpr ‹Nonempty ι›))
  rw [bootstrapSupport, div_eq_one_iff_eq hk, Nat.cast_inj]
  exact supportCount_eq_card_iff T s

/-- 支持计数为零 ⟺ 没有一棵树展示 `s`。 -/
theorem supportCount_eq_zero_iff {ι : Type*} [Fintype ι] [DecidableEq ι]
    (T : ι → Cladogram X) (s : Split X) :
    supportCount T s = 0 ↔ ∀ i, ¬ (T i).IsSplitOf s := by
  classical
  have h : supportCount T s = (Finset.univ.filter fun i => (T i).IsSplitOf s).card := rfl
  rw [h, Finset.card_eq_zero, ← Finset.not_nonempty_iff_eq_empty]
  exact ⟨fun h i hi => h ⟨i, Finset.mem_filter.mpr ⟨Finset.mem_univ i, hi⟩⟩,
         fun h ⟨i, hi⟩ => h i (Finset.mem_filter.mp hi).2⟩

/-- ★ **支持度 `= 0` ⟺ 没有一次重抽样展示它**（下界取到的唯一方式）。 -/
theorem bootstrapSupport_eq_zero_iff {ι : Type*} [Fintype ι] [DecidableEq ι] [Nonempty ι]
    (T : ι → Cladogram X) (s : Split X) :
    bootstrapSupport T s = 0 ↔ ∀ i, ¬ (T i).IsSplitOf s := by
  have hk : ((Fintype.card ι : ℕ) : ℚ) ≠ 0 := by
    exact_mod_cast (ne_of_gt (Fintype.card_pos_iff.mpr ‹Nonempty ι›))
  rw [bootstrapSupport, div_eq_zero_iff, Nat.cast_eq_zero, supportCount_eq_zero_iff]
  simp [hk]

/-- 算术小引理：`(1/2)·(2a) = a`。

⚠️ 本文件刻意**不用** `ring` / `linarith`（不在 `Phylo.ConsensusExtra` 的 import 闭包内），
故这条与 §5 的 `div_lt_div_iff₀` 用法都写成显式引理。 -/
theorem half_mul_two_mul (a : ℚ) : (1 / 2 : ℚ) * (2 * a) = a := by
  rw [← mul_assoc, show (1 / 2 : ℚ) * 2 = 1 by norm_num, one_mul]

/-! ## §3 阈值桥与多数共识（L736–753） -/

/-- ★★ **阈值桥**：`bootstrapSupport > 1/2` **就是**库内 `IsMajority`
（`Phylo/Consensus.lean:40`，即 Margush–McMorris 1981 的严格多数）。

这把 Felsenstein 的 bootstrap 口径接到库内既有的多数共识零件上，
是本文件后续相容性 / 共识树存在两条定理的**唯一**接口。 -/
theorem isMajority_iff_half_lt_bootstrapSupport {ι : Type*} [Fintype ι] [DecidableEq ι]
    [Nonempty ι] (T : ι → Cladogram X) (s : Split X) :
    IsMajority T s ↔ 1 / 2 < bootstrapSupport T s := by
  have hk : (0 : ℚ) < (Fintype.card ι : ℚ) := by
    exact_mod_cast (Fintype.card_pos_iff.mpr ‹Nonempty ι› : 0 < Fintype.card ι)
  rw [IsMajority, bootstrapSupport, lt_div_iff₀ hk]
  constructor
  · intro h
    have h2 : (Fintype.card ι : ℚ) < ((2 * supportCount T s : ℕ) : ℚ) := by exact_mod_cast h
    push_cast at h2
    have h3 := mul_lt_mul_of_pos_left h2 (show (0 : ℚ) < 1 / 2 by norm_num)
    rwa [half_mul_two_mul (supportCount T s : ℚ)] at h3
  · intro h
    have h3 := mul_lt_mul_of_pos_left h (show (0 : ℚ) < 2 by norm_num)
    rw [← mul_assoc, show (2 : ℚ) * (1 / 2) = 1 by norm_num, one_mul] at h3
    have h2 : (Fintype.card ι : ℚ) < ((2 * supportCount T s : ℕ) : ℚ) := by
      push_cast
      exact h3
    exact_mod_cast h2

/-- 把「按权重向量建树」的规则提升为「按重抽样建树」的树族。

⚠️ `Tree` 是**给定的**建树规则（Felsenstein L1294–1299 的 "run the phylogeny estimation
program with those weights"）。本文件对 `Tree` **不作任何假设** —— 这正是 bootstrap 能被
用在任何建树方法上的原因，也意味着不可能从数据推出它的性质。 -/
def resampleTrees {n : ℕ} (Tree : (Fin n → ℕ) → Cladogram X) :
    Resample n → Cladogram X :=
  fun σ => Tree (weightOf σ)

/-- 重抽样空间的基数 = `n ^ n`（每次从 `n` 个字符里抽，共抽 `n` 次）。 -/
theorem card_resample (n : ℕ) : Fintype.card (Resample n) = n ^ n := by
  simp [Resample]

/-- ★★ **支持度 `> 1/2` 的 split 两两相容**（鸽笼原理）。

两支持集大小之和 `> r` ⟹ 交于一棵树 `T i`；`T i` 的 split 系统两两相容
（`pairwiseCompatible`）⟹ `s`、`t` 相容。 -/
theorem bootstrap_supported_compatible {ι : Type*} [Fintype ι] [DecidableEq ι] [Nonempty ι]
    (T : ι → Cladogram X) {s t : Split X}
    (hs : 1 / 2 < bootstrapSupport T s) (ht : 1 / 2 < bootstrapSupport T t) :
    Split.Compatible s t :=
  majority_compatible T s t
    ((isMajority_iff_half_lt_bootstrapSupport T s).mpr hs)
    ((isMajority_iff_half_lt_bootstrapSupport T t).mpr ht)

/-- ★★★ **bootstrap 多数共识树存在**（Felsenstein L743–753）。

> "If we take the set of phylogenies that result from analyzing a series of bootstrap samples
> and make a majority-rule consensus tree, recording on it how often each subset appears ...
> The majority-rule consensus tree itself can be considered to be an overall bootstrap
> estimate of the phylogeny."

对任一重抽样树族 `T`，存在一棵树展示**所有支持度 `> 1/2` 的非平凡 split**。
证明 = `bootstrap_supported_compatible`（相容性）+ 库内 `majority_consensus_exists`
（`Phylo/Consensus.lean:98`，Aho–Buneman）。 -/
theorem bootstrap_majority_consensus_exists {ι : Type*} [Fintype ι] [DecidableEq ι]
    [Nonempty ι] (T : ι → Cladogram X) (h2 : 2 ≤ Fintype.card X) :
    ∃ Tr : RootedTree.{u, u} X, ∀ s : Split X,
      1 / 2 < bootstrapSupport T s → 2 ≤ s.sideA.card → 2 ≤ s.sideB.card →
        Tr.DisplaysSplit s := by
  classical
  obtain ⟨Tr, hTr⟩ := majority_consensus_exists T h2
  refine ⟨Tr, fun s hs hA hB => hTr s ?_⟩
  rw [mem_majoritySplits]
  exact ⟨(isMajority_iff_half_lt_bootstrapSupport T s).mpr hs, hA, hB⟩

/-! ## §4 重抽样下的期望（★★★） -/

/-- **固定一个坐标后其余坐标自由**：`{σ | σ j = i}` 与「除 `j` 外所有坐标上的函数」
一一对应，故基数 `= n ^ (n-1)`。 -/
theorem card_fiber_eq (n : ℕ) (j i : Fin n) :
    Fintype.card {σ : Resample n // σ j = i} = n ^ (n - 1) := by
  let e : {σ : Resample n // σ j = i} ≃ ({k : Fin n // k ≠ j} → Fin n) :=
    { toFun := fun σ k => σ.1 k.1
      invFun := fun g => ⟨fun k => if h : k = j then i else g ⟨k, h⟩, by simp⟩
      left_inv := by
        intro σ
        apply Subtype.ext
        funext k
        by_cases h : k = j
        · subst h
          simp [σ.2]
        · simp [h]
      right_inv := by
        intro g
        funext k
        simp [k.2] }
  rw [Fintype.card_congr e, Fintype.card_fun, Fintype.card_fin]
  congr 1
  rw [Fintype.card_subtype]
  have hf : (Finset.univ.filter fun k : Fin n => k ≠ j) = Finset.univ.erase j := by
    ext k
    simp [Finset.mem_erase]
  rw [hf, Finset.card_erase_of_mem (Finset.mem_univ j), Finset.card_univ, Fintype.card_fin]

/-- ★★★ **重抽样下字符权重的期望 = 原数据的经验频率**。

全部 `n ^ n` 次重抽样的等可能枚举上 `∑_σ weightOf σ i = n ^ n`，
即 `E[weightOf · i] = n ^ n / n ^ n = 1` —— 恰是「均匀抽 `n` 次」的均值
（`n · (1/n) = 1`），也就是**原数据里字符 `i` 的经验频率 `1/n` 的 `n` 倍**。

这是本节**正确**的期望陈述；**错误**版本（「支持度的期望 = 原数据的频率」）见文件头反例 2。 -/
theorem sum_weightOf_over_resamples {n : ℕ} (i : Fin n) :
    ∑ σ : Resample n, weightOf σ i = n ^ n := by
  classical
  have h : ∀ σ : Resample n, weightOf σ i = ∑ j : Fin n, if σ j = i then 1 else 0 := by
    intro σ
    simp only [weightOf, Finset.card_filter]
  have h2 : ∀ j : Fin n, (∑ σ : Resample n, if σ j = i then 1 else 0) = n ^ (n - 1) := by
    intro j
    rw [← Finset.card_filter, ← Fintype.card_subtype]
    exact card_fiber_eq n j i
  rw [Finset.sum_congr rfl fun σ _ => h σ, Finset.sum_comm,
    Finset.sum_congr rfl fun j _ => h2 j, Finset.sum_const, Finset.card_univ, Fintype.card_fin]
  rcases n with _ | m
  · exact absurd i.isLt (by omega)
  · simp [Nat.pow_succ, Nat.mul_comm]

/-- ★★★ **有限 bootstrap 均值恒等式**：任何**对字符线性**的统计量，
在全部 `n ^ n` 次重抽样上的**平均**恰等于它在**原数据**上的值：

```text
E[∑ᵢ weightOf σ i · cᵢ] = ∑ᵢ cᵢ        （因为 E[weightOf · i] = 1）
```

⚠️ **线性是本质的**：对非线性的 `c ↦ 1{s ∈ Tree(权重向量)}`（真实建树规则）
本恒等式**不成立** —— 这正是文件头反例 2，§5 给出机器验证的实例。 -/
theorem expected_linear_statistic_eq_original {n : ℕ} (hn : 0 < n) (c : Fin n → ℚ) :
    (Fintype.card (Resample n) : ℚ)⁻¹ *
        (∑ σ : Resample n, ∑ i : Fin n, (weightOf σ i : ℚ) * c i)
      = ∑ i : Fin n, c i := by
  have hN : (Fintype.card (Resample n) : ℚ) = (n : ℚ) ^ n := by
    rw [card_resample]
    push_cast
    rfl
  have hw : ∀ i : Fin n, (∑ σ : Resample n, (weightOf σ i : ℚ)) = (n : ℚ) ^ n := by
    intro i
    rw [← Nat.cast_sum, sum_weightOf_over_resamples i]
    push_cast
    rfl
  have hNne : ((n : ℚ) ^ n) ≠ 0 := by
    have hn' : (n : ℚ) ≠ 0 := by exact_mod_cast ne_of_gt hn
    exact pow_ne_zero n hn'
  have h1 : ∑ σ : Resample n, ∑ i : Fin n, (weightOf σ i : ℚ) * c i
      = ∑ i : Fin n, (n : ℚ) ^ n * c i := by
    rw [Finset.sum_comm]
    refine Finset.sum_congr rfl fun i _ => ?_
    rw [← Finset.sum_mul, hw i]
  rw [hN, h1, ← Finset.mul_sum, ← mul_assoc, inv_mul_cancel₀ hNne, one_mul]

/-! ## §5 ★C 最小例子：4 taxa、3 字符、27 次重抽样

**设定**（L289–307 + L1276–1299）：4 个物种 `Fin 4`、3 个字符 `Fin 3`；
第 `i` 个字符支持 `Fin 4` 上第 `i` 个 2|2 split。重抽样 = 从 3 个字符里**有放回**抽 3 次，
共 `3³ = 27` 个等可能结果（`Resample 3`）。

**建树规则**（L1294–1299 的确定性输出层）：报告在重抽样中占**严格多数**的字符的 split；
无严格多数（原数据 `(1,1,1)`）时取下标最小者。

**文献接口**：L746–747 的 "recording on it how often each subset appears" 需要的正是
「这次重抽样里含不含 `s`」这个**是/否**，所以下面的 `occ` 层与真实程序（PHYLIP，
L1313–1321）同构；`supportCount_resampleTrees_eq_ruleSupportCount` 是它与树层的桥。 -/

/-- `Fin 4` 上的 2|2 split `{0,1}|{2,3}`。 -/
def fourAB : Split (Fin 4) where
  parts := fun i => if i = (0 : Fin 2) then {0, 1} else {2, 3}
  pairwise_disjoint := by decide
  union_eq_univ := by decide
  nonempty := by decide

/-- `Fin 4` 上的 2|2 split `{0,2}|{1,3}`。 -/
def fourAC : Split (Fin 4) where
  parts := fun i => if i = (0 : Fin 2) then {0, 2} else {1, 3}
  pairwise_disjoint := by decide
  union_eq_univ := by decide
  nonempty := by decide

/-- `Fin 4` 上的 2|2 split `{0,3}|{1,2}`。 -/
def fourAD : Split (Fin 4) where
  parts := fun i => if i = (0 : Fin 2) then {0, 3} else {1, 2}
  pairwise_disjoint := by decide
  union_eq_univ := by decide
  nonempty := by decide

/-- **建树规则的输出层**：报告在 `n` 次重抽样中权重占**严格多数**（`2·wᵢ > n`）的字符的
split；无多数时取下标最小者。这就是 L1294–1299「用这些权重跑程序」的确定性实现。 -/
def selMajority (n : ℕ) (w : Fin 3 → ℕ) : Split (Fin 4) :=
  if 2 * w 0 > n then fourAB
  else if 2 * w 1 > n then fourAC
  else if 2 * w 2 > n then fourAD
  else fourAB

/-- **建树规则的输出层（一般接口）**：`occ w s = true` 表示「按权重 `w` 建出的树含 `s`」。

L746–747 的 "recording on it how often each subset appears" 需要的正是这个**是/否**，
不需要树的本身（PHYLIP 接口见 L1313–1321）。 -/
def ruleSupportCount {n : ℕ} {X : Type*} [Fintype X] [DecidableEq X]
    (occ : (Fin n → ℕ) → Split X → Bool) (s : Split X) : ℕ :=
  (Finset.univ.filter fun σ : Resample n => occ (weightOf σ) s = true).card

/-- 输出层的支持度（比例版）。 -/
noncomputable def ruleSupport {n : ℕ} {X : Type*} [Fintype X] [DecidableEq X]
    (occ : (Fin n → ℕ) → Split X → Bool) (s : Split X) : ℚ :=
  (ruleSupportCount occ s : ℚ) / (Fintype.card (Resample n) : ℚ)

/-- ★★ **桥**：输出层与真实建树规则一致时，两条支持计数定义**相等**。 -/
theorem supportCount_resampleTrees_eq_ruleSupportCount {n : ℕ}
    (Tree : (Fin n → ℕ) → Cladogram X) (occ : (Fin n → ℕ) → Split X → Bool) (s : Split X)
    (h : ∀ w, ((Tree w).IsSplitOf s ↔ occ w s = true)) :
    supportCount (resampleTrees Tree) s = ruleSupportCount occ s := by
  classical
  have hf : (Finset.univ.filter fun σ : Resample n => (resampleTrees Tree σ).IsSplitOf s)
      = (Finset.univ.filter fun σ : Resample n => occ (weightOf σ) s = true) :=
    Finset.filter_congr fun σ _ => h (weightOf σ)
  rw [supportCount, ruleSupportCount, hf]

/-- 桥的比例版。 -/
theorem bootstrapSupport_resampleTrees_eq_ruleSupport {n : ℕ}
    (Tree : (Fin n → ℕ) → Cladogram X) (occ : (Fin n → ℕ) → Split X → Bool) (s : Split X)
    (h : ∀ w, ((Tree w).IsSplitOf s ↔ occ w s = true)) :
    bootstrapSupport (resampleTrees Tree) s = ruleSupport occ s := by
  rw [bootstrapSupport, ruleSupport, supportCount_resampleTrees_eq_ruleSupportCount Tree occ s h]

/-- ★★★ **最小例子的精确计数**：27 次重抽样中，恰好 **13** 次报告 `fourAB`。

（`decide` 逐项枚举 `3³ = 27` 个抽样映射；**无随机数、无 Monte Carlo** ——
这正是「用枚举全部重抽样结果代替随机」的做法。） -/
theorem minimal_example_count :
    ruleSupportCount (fun w s => decide (selMajority 3 w = s)) fourAB = 13 := by
  decide

/-- 重抽样次数 `= 3³ = 27`。 -/
theorem card_resample_three : Fintype.card (Resample 3) = 27 := by decide

/-- ★★★ 最小例子里 `fourAB` 的 bootstrap 支持度恰为 `13/27`。 -/
theorem minimal_example_support :
    ruleSupport (fun w s => decide (selMajority 3 w = s)) fourAB = 13 / 27 := by
  rw [ruleSupport, minimal_example_count, card_resample_three]
  norm_num

/-- ★B **反例 1（本文件核心）**：`13/27 < 1/2`。

所以 `fourAB` **不在**多数共识树里 —— 尽管**原数据报告的正是它**
（`(1,1,1)` 无严格多数 ⟹ 落到 `fourAB`，见 `minimal_example_original_split`）。 -/
theorem minimal_example_support_lt_half :
    ruleSupport (fun w s => decide (selMajority 3 w = s)) fourAB < 1 / 2 := by
  rw [minimal_example_support,
    div_lt_div_iff₀ (show (0 : ℚ) < 27 by norm_num) (show (0 : ℚ) < 2 by norm_num)]
  exact_mod_cast (show (13 : ℕ) * 2 < 1 * 27 by norm_num)

/-- ★B **原数据报告的 split**：恒等重抽样（每个字符恰抽一次）的权重向量是 `(1,1,1)`，
无严格多数，落到 `fourAB`。 -/
theorem minimal_example_original_split :
    selMajority 3 (weightOf (id : Resample 3)) = fourAB := by
  decide

/-- ★B／★★★ **把最小例子接到抽象层**：任何「`fourAB` 出现 ⟺ 规则报告 `fourAB`」的
真实建树规则 `Tree`，其重抽样树族上 `fourAB` 的 `bootstrapSupport` 就是 `13/27 < 1/2`。

**这就是反例 2 的机器验证形式**：原数据的树 `Tree (1,1,1)` 含 `fourAB`（频率 `1`），
但 `bootstrapSupport` 的**期望**只有 `13/27 < 1` —— 故
「重抽样下支持度的期望 = 原数据的频率」**为假**。 -/
theorem minimal_example_treeSupport_lt_half (Tree : (Fin 3 → ℕ) → Cladogram (Fin 4))
    (h : ∀ w, (Tree w).IsSplitOf fourAB ↔ selMajority 3 w = fourAB) :
    bootstrapSupport (resampleTrees Tree) fourAB < 1 / 2 := by
  rw [bootstrapSupport_resampleTrees_eq_ruleSupport Tree
    (fun w s => decide (selMajority 3 w = s)) fourAB (fun w => by rw [h w]; simp)]
  exact minimal_example_support_lt_half

/-! ## §6 显式缺口（`def … : Prop`，**不是** `axiom`，也**不是** `sorry`） -/

/-- ❌ **缺口 M（多项式系数记账）**：和恰为 `n` 的权重向量 `w`，恰由 `n! / ∏ᵢ (wᵢ)!`
个抽样映射 `σ` 实现 —— 即重抽样计数就是**多项式分布型计数**（L1288–1292 给出的五条
20-字符权重串正是这种计数的实例）。写成无除法的形式：

```text
#{σ : Resample n | weightOf σ = w} · ∏ᵢ (wᵢ)!  =  n!
```

**未证**：缺的是「多重集排列数」的记账（`Finset` 的重排与多项式系数之间的双射）。
本文件只证了**不依赖它**的那部分（`sum_weightOf`、`sum_weightOf_over_resamples`、
以及 `n = 3` 直接枚举的 `minimal_example_count`）。**本文件不在任何证明中使用它。** -/
def multinomial_weight_count_gap : Prop :=
  ∀ (n : ℕ) (w : Fin n → ℕ), IsBootstrapWeight w →
    (Finset.univ.filter fun σ : Resample n => weightOf σ = w).card
      * (∏ i, Nat.factorial (w i)) = Nat.factorial n

/-- ❌ **缺口 C（支持度 → 置信度）**：把 `bootstrapSupport`（重抽样树族中的**频率**）
读成「真树含该 split」的**置信度**，需要三样本库都没有的零件：

1. 字符 **iid** 的概率空间 —— `Phylo.Stat.EmpiricalConvergence` 把它**公理化**了
   （该文件 §4 缺口 K：本版 Mathlib 无可数无限乘积测度）；
2. 树空间上的概率测度与「重抽样分布 → 真实抽样分布」的弱收敛（L261–263、L275–284）；
3. 建树估计量的相容性（L776–783 / L755–765：方法不相容时 bootstrap **不修正**）。

本 `Prop` 只把「还欠什么」记成账目（与 `Phylo/Stat/SplitProbabilities.lean` 的缺口 G1–G3
同一体例）：存在概率空间与「真树」选择，使高频 `split` 与真树相容。
⚠️ 它**弱于**真正的数学内容（真正的缺口是概率空间必须由字符的 iid 分布**诱导**），
且**本文件不在任何证明中使用它。** -/
def bootstrap_confidence_gap : Prop :=
  ∃ (Ω : Type) (TrueSplit : Ω → Split (Fin 4)) (p : Ω → Split (Fin 4) → ℚ),
    (∀ ω (s : Split (Fin 4)), 0 ≤ p ω s ∧ p ω s ≤ 1) ∧
    (∀ ω, 1 / 2 < p ω (TrueSplit ω)) ∧
    ∀ (ω : Ω) (s : Split (Fin 4)), 1 / 2 < p ω s → Split.Compatible s (TrueSplit ω)

/-! ## §7 反空真（★B）

下面每条都给出定义**真的能被满足**的见证，防止 `bootstrapSupport` / `IsBootstrapWeight` /
三个候选 split 成为空转定义。 -/

/-- **非空真**：恒等重抽样（每个字符恰抽一次）的权重向量是 `(1,1,1)` —— 即原数据。 -/
theorem weightOf_id_three : weightOf (id : Resample 3) = fun _ => 1 := by
  funext i
  fin_cases i <;> decide

/-- **非空真**：`(1,1,1)` 是合法权重向量。 -/
theorem isBootstrapWeight_three : IsBootstrapWeight (fun _ : Fin 3 => 1) := by
  show (∑ i : Fin 3, (fun _ : Fin 3 => 1) i) = 3
  decide

/-- **非空真**：`(3,0,0)` 也是合法权重向量（三次都抽中字符 `0` 的极端重抽样）。 -/
theorem isBootstrapWeight_three_extreme :
    IsBootstrapWeight (fun i : Fin 3 => if i = 0 then 3 else 0) := by
  show (∑ i : Fin 3, (if i = 0 then 3 else 0 : ℕ)) = 3
  decide

/-- **非空真**：三个候选 split 两两不同。 -/
theorem fourAB_ne_fourAC : fourAB ≠ fourAC := by decide

/-- **非空真**：三个候选 split 两两不同。 -/
theorem fourAB_ne_fourAD : fourAB ≠ fourAD := by decide

/-- **非空真**：三个候选 split 两两不同。 -/
theorem fourAC_ne_fourAD : fourAC ≠ fourAD := by decide

/-- ★ **4 元 3-split 障碍**：`{0,1}|{2,3}` 与 `{0,2}|{1,3}` **不相容**。

这条使「按权重选出一个 split」与「建出一棵树」相容：一棵树的 split 系统两两相容，
故它至多含三者之一 —— 于是 §5 的 `occ` 层与树层一致（§5 的桥定理）。
（同族零件：`Phylo/SplitWeak.lean` 的 `hasConflictingQuartet_four` 与
`Phylo/Stat/Stability.lean` 的 `IsTrueChoice`。） -/
theorem not_compatible_fourAB_fourAC : ¬ Split.Compatible fourAB fourAC := by
  unfold Split.Compatible
  decide

/-- ★ **4 元 3-split 障碍**：`{0,1}|{2,3}` 与 `{0,3}|{1,2}` **不相容**。 -/
theorem not_compatible_fourAB_fourAD : ¬ Split.Compatible fourAB fourAD := by
  unfold Split.Compatible
  decide

/-- ★ **4 元 3-split 障碍**：`{0,2}|{1,3}` 与 `{0,3}|{1,2}` **不相容**。 -/
theorem not_compatible_fourAC_fourAD : ¬ Split.Compatible fourAC fourAD := by
  unfold Split.Compatible
  decide

end Phylo.Stat.Bootstrap
